name: hello world
on:
  push:
    branches: [feature/github-actions]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo Hello world
